contact_links:
  - name: "\U0001F5E3 All other questions and general discussion"
    url: https://github.com/UtrechtUniversity/dataprivacyhandbook/discussions
    about: Talk to us through GitHub Discussions! 💛
